[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
coin_flip = "4Txje2aJHy3easv6AopsmSnARknvkJ6VXoJSi46pKnRF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
